global:
    scrape_interval: 4s
    evaluation_interval: 4s

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: "otel"
      metrics_path: /metrics
      static_configs:
          - targets: ["otel-collector:8889"]

    - job_name: aggregated-trace-metrics
      static_configs:
          - targets: ["jaeger:8889"]
