{
 "title": "Latency Dashboard",
 "tags": [
  "eShop",
  "API",
  "Monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Ordering API Latency (p95)",
   "type": "timeseries",
   "description": "Shows the average duration of basket operations over time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route) (rate(http_server_request_duration_seconds_bucket{exported_job=\"ordering-api\"}[5m])))",
     "legendFormat": "{{operation}} (p95)"
    }
   ]
  },
  {
   "title": "WebAPP Latency (p95)",
   "type": "timeseries",
   "description": "Shows the average duration of basket operations over time",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route) (rate(http_server_request_duration_seconds_bucket{exported_job=\"webapp\"}[5m])))",
     "legendFormat": "{{operation}} (p95)"
    }
   ]
  },
  {
   "title": "Identity API Latency (p95)",
   "type": "timeseries",
   "description": "Shows the average duration of basket operations over time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route) (rate(http_server_request_duration_seconds_bucket{exported_job=\"identity-api\"}[5m])))",
     "legendFormat": "{{operation}} (p95)"
    }
   ]
  },
  {
   "title": "Catalog API Latency (p95)",
   "type": "timeseries",
   "description": "Shows the average duration of basket operations over time",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route) (rate(http_server_request_duration_seconds_bucket{exported_job=\"catalog-api\"}[5m])))",
     "legendFormat": "{{operation}} (p95)"
    }
   ]
  },
  {
   "title": "Basket APILatency (p95)",
   "type": "timeseries",
   "description": "Shows the average duration of basket operations over time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route) (rate(http_server_request_duration_seconds_bucket{exported_job=\"basket-api\"}[5m])))",
     "legendFormat": "{{operation}} (p95)"
    }
   ]
  }
 ]
}