{
 "title": "Load Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Identity Gateway CPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(irate(dotnet_process_cpu_time_seconds_total{exported_job=\"identity-api\"}[5m])) / (max(dotnet_process_cpu_count{exported_job=\"identity-api\"}) / 2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web App CPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(irate(dotnet_process_cpu_time_seconds_total{exported_job=\"webapp\"}[5m])) / (max(dotnet_process_cpu_count{exported_job=\"webapp\"}) / 2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrent User Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(exported_job) (rate(http_client_open_connections[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}